splash = false
ipc = on

# hyprpaper v0.8.x BLOK söz dizimi kullanır (preload=/wallpaper= DEĞİL!)
# monitor =  (boş) -> tüm monitörlere uygulanır
wallpaper {
    monitor = DP-3
    path = $HOME/Pictures/Wallpapers/samurai.png
}

wallpaper {
    monitor = DP-2
    path = $HOME/Pictures/Wallpapers/katana.png
}

wallpaper {
    monitor = DP-1
    path = $HOME/Pictures/Wallpapers/wall.png
}

# Tek tek atamak istersen her monitör için ayrı blok:
# wallpaper {
#     monitor = DP-3
#     path = $HOME/Pictures/Wallpapers/baska.png
# }
