-- Generated by nwg-displays on 2026-06-20 at 17:04:16. Do not edit manually.

hl.monitor({
    output = "DP-1",
    mode = "1920x1080@59.93",
    position = "388x1875",
    scale = 1.0
})
hl.monitor({
    output = "DP-2",
    mode = "1920x1080@60.0",
    position = "4868x1322",
    scale = 1.0,
    transform = 1
})
hl.monitor({
    output = "DP-3",
    mode = "2560x1440@165.0",
    position = "2308x1515",
    scale = 1.0
})
